### ISSUE TITLE
FYI - Parinfer now available in Emacs Lisp

### ISSUE THREAD

**Issue by oakmac** [edpaget/parinfer-mode#5]
The core Parinfer algorithm is now available as an Emacs Lisp library: https://github.com/oakmac/parinfer-elisp

**Comment by edpaget** [comment]
Thanks updated to use that https://github.com/edpaget/parinfer-mode/commit/c640934f796d4e400a072262690527bb32e9cb65

It'd be awesome if you could release the lib on melpa so this could depend on it that way instead of having to include the file. I don't mind helping you get it uploaded if you need it.

**Comment by oakmac** [comment]
Awesome work! Help with MELPA would be appreciated: https://github.com/oakmac/parinfer-elisp/issues/8
